#include<stdio.h>
int main()
{
        int n1,n2,n3;
        printf("Enter 1st no.=");
        scanf("%d",&n1);
        printf("Enter 2st no.=");
        scanf("%d",&n2);
        printf("Enter 3st no.=");
        scanf("%d",&n3);
        
        if(n1>n2)
        {
            if(n2>n3)
            {
                printf("%d>%d=%d",n1,n2,n3);
            }
        }
        if(n1>n3)
        {
            if(n3>n2)
            {
                printf("%d>%d>%d",n1,n3,n2);
            }
        }
        if(n2>n1)
        {
            if(n1>n3)
            {
                printf("%d>%d>%d",n2,n1,n3);
            }
        }
        if(n2>n3)
        {
            if(n3>n1)
            {
                printf("%d>%d>%d",n2,n3,n1);
            }
        }
        if(n3>n1)
        {
            if(n1>n2)
            {
                printf("%d>%d>%d",n3,n1,n2);
            }
        }
        if(n3>n2)
        {
            if(n2>n1)
            {
                printf("%d>%d>%d",n3,n2,n1);
            }
        }
        if(n1==n2)
        {
            if(n2==n3)
            {
            printf("%d=%d=%d",n1,n2,n3);
            }
        }
        if(n1==n2)
        {
            if(n2>n3)
            {
                printf("%d=%d>%d",n1,n2,n3);
            }
            if(n2<n3)
            {
                printf("%d=%d<%d",n1,n2,n3);
            }
        }
        if(n2==n3)
        {
            if(n3>n1)
            {
                printf("%d=%d>%d",n2,n3,n1);
            }
            if(n3<n1)
            {
                printf("%d=%d<%d",n2,n3,n1);
            }
        }
        if(n1==n3)
        {
            if(n3>n2)
            {
                printf("%d=%d>%d",n1,n3,n2);
            }
            if(n3<n2)
            {
                printf("%d=%d<%d",n1,n3,n2);
            }
        }
        return 0;
}